// @ts-check
// The sidebar is generated automatically from the docs folder structure.
// Each subfolder contributes a category via its `_category_.json`, and ordering
// within a category is controlled by the `sidebar_position` frontmatter on each
// page. This keeps the navigation in lock-step with the file tree.
//
// Docs: https://docusaurus.io/docs/sidebar/autogenerated

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
